# Site settings
title: Transit Land
email: transitland@mapzen.com
description: > # A community edited dataservice aggregating transit networks across metropolitan and rural areas around the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://transit.land/" # the base hostname & protocol for your site
twitter_username: transitland
github_username:  transitland

# Build settings
markdown: kramdown
exclude: [vendor] # https://github.com/jekyll/jekyll/issues/2938

